This project is a lab of 2 small L3LS DC's with a DCI consisting of two links
    US_DC is the name for the both fabrics
    SJ is the San Jose fabric  
    AS is the Ashburn fabric

The yaml for this project uses the following structure: 
    group_var directories
        US_DC
            dci_p2p.yml - point to point DCI links
            common.yml - configuration common to both DC's
        SJ_NETWORKS
            networks.yml - overlay tenant networks
        SJ_FABRIC
            sj_fabric.yml - San Jose Fabric
            sj_common.yml - configuration specific to San Jose
        SJ_ENDPOINTS
            endpoints.yml - configuration for endpoint ports
            port-profiles.yml - templates for ports
        AS_NETWORKS
            networks.yml - overlay tenant networks
        AS_FABRIC
            as_fabric.yml - Ashburn Fabric
            as_common.yml - configuration specific to Ashburn
        AS_ENDPOINTS
            endpoints.yml - configuration for endpoint ports
            port-profiles.yml - templates for ports
        CVP.yml - DHCP/ZTP configuration
        
    host_var files
        SJ-DCI1.yml - custom configuration for EVPN on SJ-DCI1 node
        SJ-DCI2.yml - custom configuration for EVPN on SJ-DCI2 node
        AS-DCI1.yml - custom configuration for EVPN on AS-DCI1 node
        AS-DCI2.yml - custom configuration for EVPN on AS-DCI2 node

For vault encryption, the sensitive fabric variables are encrypted using 'encryt_string'.  

I was unable to encrypt the CVP accounts in the inventory using either variable or file encryption.   

Variable encryption exception

**********************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: NotImplementedError: Vault encrypted variables are not supported as password yet. Use ansible vault file instead.https://docs.ansible.com/ansible/latest/user_guide/vault.html#encrypting-files-with-ansible-vault
fatal: [cv_server]: FAILED! 

File encryption exception

TASK [arista.avd.eos_config_deploy_cvp : Generate intended variables] ******************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'str' object has no attribute 'items'
fatal: [cv_server]: FAILED!
